graph LR
    BA[Business Goal:<br> Optimize pricing & production decisions through break-even analysis and cost management]
    Admin[Admin] --> G(View Calculation History)
    Admin --> H(Manage Data)

    User[User] --> A(Enter Calculation Input)
    User --> B(Upload File for Multi-Calculation)
    A --> C(Compute Break-Even Points)
    C --> D(View Calculation Results)
    C --> E(Save Calculation History)
    B --> F(Perform Batch Calculations)
    F --> D
    F --> E

    BA -.-> A
    BA -.-> B
    BA -.-> G
    BA -.-> H
